<?php

declare(strict_types=1);

function synapse_vehicle_inventory(): array
{
    return [
        [
            'name' => 'Apex GT',
            'detail' => 'Performance coupe - Petrol',
            'category' => 'performance touring',
            'image' => 'hero-coast.png',
            'width' => 1962,
            'height' => 802,
            'alt' => 'Graphite performance coupe on a coastal overlook',
            'body' => 'Coupe',
            'powertrain' => 'Petrol',
            'drive' => 'Rear-wheel drive',
            'availability' => 'Available now',
            'collection' => 'Coast road edit',
        ],
        [
            'name' => 'Vela R',
            'detail' => 'Grand touring coupe - Petrol',
            'category' => 'performance touring',
            'image' => 'tunnel-gt.png',
            'width' => 1796,
            'height' => 876,
            'alt' => 'Oxblood grand touring coupe driving through a concrete tunnel',
            'body' => 'Grand touring',
            'powertrain' => 'Petrol',
            'drive' => 'All-wheel drive',
            'availability' => 'Available now',
            'collection' => 'Long-distance picks',
        ],
        [
            'name' => 'Northline E',
            'detail' => 'SUV - Electric',
            'category' => 'electric suv',
            'image' => 'alpine-suv.png',
            'width' => 1536,
            'height' => 1024,
            'alt' => 'Silver electric SUV parked beside a lakeside cabin',
            'body' => 'SUV',
            'powertrain' => 'Electric',
            'drive' => 'Dual-motor AWD',
            'availability' => 'Available now',
            'collection' => 'Quiet weekender',
        ],
        [
            'name' => 'Harbor S',
            'detail' => 'City crossover - Electric',
            'category' => 'electric city suv',
            'image' => 'alpine-suv.png',
            'width' => 1536,
            'height' => 1024,
            'alt' => 'Silver electric SUV parked beside a lakeside cabin',
            'body' => 'Crossover',
            'powertrain' => 'Electric',
            'drive' => 'Rear-wheel drive',
            'availability' => 'Available to order',
            'collection' => 'Urban daily',
        ],
        [
            'name' => 'Monarch T',
            'detail' => 'Touring sedan - Petrol',
            'category' => 'touring city',
            'image' => 'tunnel-gt.png',
            'width' => 1796,
            'height' => 876,
            'alt' => 'Oxblood grand touring coupe driving through a concrete tunnel',
            'body' => 'Sedan',
            'powertrain' => 'Petrol',
            'drive' => 'Front-engine touring',
            'availability' => 'Viewing this week',
            'collection' => 'Open-road catalogue',
        ],
        [
            'name' => 'Cinder RS',
            'detail' => 'Track coupe - Petrol',
            'category' => 'performance collector',
            'image' => 'hero-coast.png',
            'width' => 1962,
            'height' => 802,
            'alt' => 'Graphite performance coupe on a coastal overlook',
            'body' => 'Coupe',
            'powertrain' => 'Petrol',
            'drive' => 'Rear-wheel drive',
            'availability' => 'By appointment',
            'collection' => 'Collector shelf',
        ],
    ];
}
